name: x86-release-build

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - run: |
          npx update-browserslist-db@latest && yarn config set strict-ssl false && yarn && yarn dist
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.access_token }}
